const images = {
    pic : require("./asset/pic.jpg"),
    bali : require("./asset/bali.jpg"),
    kyoto : require("./asset/kyoto.jpg"),
    goldengatepark : require("./asset/goldengatepark.jpg"),
    park : require("./asset/park.jpeg"),
    academyOfScience : require("./asset/academyOfScience.png"),
    academysciencediver : require("./asset/academysciencediver.jpg"),
    downtown : require("./asset/downtown.jpg"),
    chinatown : require("./asset/chinatown.jpg"),
    salesforce : require("./asset/salesforce.jpg"),
    sushi : require("./asset/sushi.jpg"),
    burj : require("./asset/burj.png"),
    frankfurt : require("./asset/frankfurt.jpg"),
    opera : require("./asset/opera.jpg"),
    morocco : require("./asset/morocco.png"),
    groupburgers : require("./asset/groupburgers.png"),
    curry : require("./asset/curry.png"),
    boca : require("./asset/boca.png"),
    ramen : require("./asset/ramen.png"),
    kbbq : require("./asset/kbbq.png"),
    boats : require("./asset/boats.jpg"),
    nepal : require("./asset/nepal.jpg")
}
export {images};
